OPENAI_API_KEY = "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"

[connections.snowpark]
user = "SHAWNMAI"
role = "ACCOUNTADMIN"
user_read = "trevor1"
role_read = "trevor"
password = "Nekgef-dijdum-3jekte"
warehouse = "COMPUTE_WH"
account = "EWQBGGY-UK00228"
database = "FINANCE"
schema = "CREDIT_CARD"